/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        url = uri("https://repository.apache.org/content/repositories/snapshots/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
    maven {
        url = uri("https://packages.confluent.io/maven/")
    }
}

dependencies {
    api(libs.org.apache.beam.beam.sdks.java.core)
    api(libs.org.apache.beam.beam.sdks.java.io.google.cloud.platform)
    api(libs.org.apache.beam.beam.sdks.java.myextensions.python)
    api(libs.org.apache.beam.beam.sdks.java.io.kafka)
    api(libs.com.google.api.client.google.api.client)
    api(libs.com.google.apis.google.api.services.bigquery)
    api(libs.com.google.http.client.google.http.client)
    api(libs.com.google.apis.google.api.services.pubsub)
    api(libs.joda.time.joda.time)
    api(libs.org.apache.kafka.kafka.clients)
    api(libs.org.slf4j.slf4j.api)
    api(libs.org.hamcrest.hamcrest.core)
    api(libs.org.hamcrest.hamcrest.library)
    api(libs.junit.junit)
    runtimeOnly(libs.org.slf4j.slf4j.jdk14)
    runtimeOnly(libs.org.apache.beam.beam.runners.direct.java)
    runtimeOnly(libs.org.apache.beam.beam.runners.portability.java)
    testImplementation(libs.org.mockito.mockito.core)
}

group = "org.example"
version = "0.1"
description = "word-count-beam"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

if (project.hasProperty("dataflow-runner")) {
    dependencies {
        runtimeOnly("org.apache.beam:beam-runners-google-cloud-dataflow-java:2.60.0")
    }
}

tasks.register<JavaExec>("execute") {
  mainClass.set(System.getProperty("mainClass"))
  classpath = sourceSets.main.get().runtimeClasspath
}

// task runSingle(type: JavaExec) {
//     mainClass = 'org.apache.beam.examples.MinimumWordCountM' // Replace with your class
//     classpath = sourceSets.main.runtimeClasspath
//     args = []
// }
 